package versions

import (
	"bytes"
	"fmt"
	"os"
	"sort"
	"strings"

	"gopkg.in/yaml.v3"
)

type Definitions struct {
	Services map[string]Service `yaml:"services"`
}

type Service struct {
	Name         string   `yaml:"-"`
	Env          string   `yaml:"env"`
	Image        string   `yaml:"image"`
	Environments []string `yaml:"environments"`
}

func Load(path string) (Definitions, error) {
	data, err := os.ReadFile(path)
	if err != nil {
		return Definitions{}, err
	}
	var defs Definitions
	if err := yaml.Unmarshal(data, &defs); err != nil {
		return Definitions{}, err
	}
	for name, svc := range defs.Services {
		svc.Name = name
		defs.Services[name] = svc
		if svc.Env == "" {
			return Definitions{}, fmt.Errorf("service %s missing env", name)
		}
		if svc.Image == "" {
			return Definitions{}, fmt.Errorf("service %s missing image", name)
		}
	}
	return defs, nil
}

func (d Definitions) ForEnvironment(env string) []Service {
	var services []Service
	for name, svc := range d.Services {
		if includes(svc.Environments, env) {
			svc.Name = name
			services = append(services, svc)
		}
	}
	sort.Slice(services, func(i, j int) bool {
		return services[i].Name < services[j].Name
	})
	return services
}

func (d Definitions) EnvFile(env string) string {
	services := d.ForEnvironment(env)
	var buf bytes.Buffer
	buf.WriteString("# Generated by fystack. Do not store secrets here.\n")
	for _, svc := range services {
		fmt.Fprintf(&buf, "%s=%s\n", svc.Env, svc.Image)
	}
	return buf.String()
}

func UpdateImages(path string, updates map[string]string) error {
	if len(updates) == 0 {
		return nil
	}
	data, err := os.ReadFile(path)
	if err != nil {
		return err
	}
	var doc yaml.Node
	if err := yaml.Unmarshal(data, &doc); err != nil {
		return err
	}
	root := documentRoot(&doc)
	services := mappingValue(root, "services")
	if services == nil {
		return fmt.Errorf("versions file missing services")
	}
	for service, image := range updates {
		serviceNode := mappingValue(services, service)
		if serviceNode == nil {
			return fmt.Errorf("service %s not found", service)
		}
		imageNode := mappingValue(serviceNode, "image")
		if imageNode == nil {
			return fmt.Errorf("service %s missing image", service)
		}
		imageNode.Kind = yaml.ScalarNode
		imageNode.Tag = "!!str"
		imageNode.Value = image
	}

	var out bytes.Buffer
	encoder := yaml.NewEncoder(&out)
	encoder.SetIndent(2)
	if err := encoder.Encode(&doc); err != nil {
		_ = encoder.Close()
		return err
	}
	if err := encoder.Close(); err != nil {
		return err
	}
	return os.WriteFile(path, out.Bytes(), 0644)
}

func documentRoot(node *yaml.Node) *yaml.Node {
	if node.Kind == yaml.DocumentNode && len(node.Content) > 0 {
		return node.Content[0]
	}
	return node
}

func mappingValue(node *yaml.Node, key string) *yaml.Node {
	if node == nil || node.Kind != yaml.MappingNode {
		return nil
	}
	for i := 0; i+1 < len(node.Content); i += 2 {
		if node.Content[i].Value == key {
			return node.Content[i+1]
		}
	}
	return nil
}

func includes(values []string, target string) bool {
	for _, value := range values {
		if strings.EqualFold(value, target) || value == "*" {
			return true
		}
	}
	return false
}
